const SMALL_CLASS_NAMES = [
    "sailboat",
    "pliers",
    "see saw",
    "garden hose",
    "cactus",
    "eyeglasses",
    "nose",
    "stairs",
    "envelope",
    "bucket",
    "fireplace",
    "swing set",
    "lantern",
    "banana",
    "spreadsheet",
    "elephant",
    "fish",
    "helicopter",
    "axe",
    "cell phone",
]

const BIG_CLASS_NAMES = [
    "sailboat",
    "pliers",
    "see saw",
    "garden hose",
    "cactus",
    "eyeglasses",
    "nose",
    "stairs",
    "envelope",
    "bucket",
    "fireplace",
    "swing set",
    "lantern",
    "banana",
    "spreadsheet",
    "elephant",
    "fish",
    "helicopter",
    "axe",
    "cell phone",
    "hammer",
    "string bean",
    "donut",
    "star",
    "radio",
    "cat",
    "diamond",
    "frog",
    "broom",
    "coffee cup",
    "speedboat",
    "paper clip",
    "bicycle",
    "map",
    "baseball",
    "tennis racquet",
    "line",
    "dishwasher",
    "paintbrush",
    "fork",
    "teddy - bear",
    "The Mona Lisa",
    "clarinet",
    "flamingo",
    "couch",
    "rainbow",
    "bed",
    "lipstick",
    "parrot",
    "ladder",
    "syringe",
    "violin",
    "megaphone",
    "car",
    "cookie",
    "rollerskates",
    "anvil",
    "goatee",
    "teapot",
    "octagon",
    "hospital",
    "bridge",
    "leg",
    "skull",
    "ear",
    "mushroom",
    "chandelier",
    "pool",
    "crown",
    "apple",
    "golf club",
    "potato",
    "calendar",
    "book",
    "trombone",
    "stove",
    "scorpion",
    "blackberry",
    "circle",
    "sheep",
    "sandwich",
    "bird",
    "bowtie",
    "wine bottle",
    "postcard",
    "power outlet",
    "chair",
    "hedgehog",
    "pants",
    "bread",
    "microwave",
    "t - shirt",
    "rabbit",
    "guitar",
    "dog",
    "bulldozer",
    "bus",
    "light bulb",
    "computer",
    "hexagon",
    "beach",
    "skateboard",
    "barn",
    "jail",
    "waterslide",
    "cooler",
    "traffic light",
    "hand",
    "harp",
    "moon",
    "toe",
    "vase",
    "cello",
    "remote control",
    "truck",
    "microphone",
    "underwear",
    "rifle",
    "drill",
    "square",
    "knee",
    "giraffe",
    "snail",
    "camouflage",
    "table",
    "alarm clock",
    "camel",
    "shorts",
    "lighthouse",
    "suitcase",
    "bottlecap",
    "tractor",
    "carrot",
    "hockey puck",
    "dumbbell",
    "shoe",
    "The Great Wall of China",
    "campfire",
    "foot",
    "flip flops",
    "monkey",
    "helmet",
    "bandage",
    "bench",
    "stethoscope",
    "grass",
    "mermaid",
    "laptop",
    "hot air balloon",
    "floor lamp",
    "cow",
    "dolphin",
    "asparagus",
    "motorbike",
    "skyscraper",
    "strawberry",
    "umbrella",
    "brain",
    "mouth",
    "zebra",
    "jacket",
    "triangle",
    "hurricane",
    "bracelet",
    "pineapple",
    "rake",
    "steak",
    "baseball bat",
    "arm",
    "popsicle",
    "flying saucer",
    "mouse",
    "horse",
    "crab",
    "piano",
    "river",
    "castle",
    "compass",
    "binoculars",
    "ceiling fan",
    "airplane",
    "scissors",
    "garden",
    "bush",
    "bathtub",
    "clock",
    "drums",
    "lobster",
    "flower",
    "diving board",
    "toothbrush",
    "saw",
    "sea turtle",
    "squiggle",
    "tooth",
    "mountain",
    "sword",
    "aircraft carrier",
    "necklace",
    "cup",
    "wine glass",
    "lighter",
    "elbow",
    "blueberry",
    "snowman",
    "broccoli",
    "sun",
    "television",
    "sock",
    "pig",
    "key",
    "parachute",
    "hot tub",
    "shark",
    "washing machine",
    "hat",
    "windmill",
    "frying pan",
    "fire hydrant",
    "toothpaste",
    "belt",
    "beard",
    "rhinoceros",
    "headphones",
    "matches",
    "knife",
    "snorkel",
    "feather",
    "duck",
    "pond",
    "paint can",
    "firetruck",
    "angel",
    "bear",
    "passport",
    "cake",
    "telephone",
    "mosquito",
    "hamburger",
    "pencil",
    "peas",
    "ant",
    "eye",
    "mailbox",
    "grapes",
    "canoe",
    "pillow",
    "The Eiffel Tower",
    "sink",
    "backpack",
    "octopus",
    "finger",
    "snowflake",
    "tent",
    "nail",
    "submarine",
    "wheel",
    "church",
    "toilet",
    "purse",
    "penguin",
    "bee",
    "streetlight",
    "van",
    "boomerang",
    "train",
    "peanut",
    "stop sign",
    "basket",
    "wristwatch",
    "ice cream",
    "pizza",
    "crocodile",
    "lollipop",
    "hockey stick",
    "soccer ball",
    "dragon",
    "camera",
    "cannon",
    "zigzag",
    "spoon",
    "pickup truck",
    "ocean",
    "bat",
    "stitches",
    "shovel",
    "palm tree",
    "mug",
    "hot dog",
    "fan",
    "sweater",
    "cruise ship",
    "cloud",
    "whale",
    "police car",
    "saxophone",
    "squirrel",
    "smiley face",
    "owl",
    "house",
    "school bus",
    "yoga",
    "spider",
    "flashlight",
    "tree",
    "swan",
    "panda",
    "ambulance",
    "calculator",
    "pear",
    "trumpet",
    "lightning",
    "animal migration",
    "dresser",
    "basketball",
    "birthday cake",
    "leaf",
    "oven",
    "house plant",
    "keyboard",
    "eraser",
    "sleeping bag",
    "moustache",
    "door",
    "hourglass",
    "crayon",
    "stereo",
    "fence",
    "roller coaster",
    "onion",
    "marker",
    "tiger",
    "screwdriver",
    "watermelon",
    "lion",
    "butterfly",
    "toaster",
    "raccoon",
    "picture frame",
    "candle",
    "face",
    "kangaroo",
    "snake",
    "tornado",
    "rain"
]

export {
    SMALL_CLASS_NAMES,
    BIG_CLASS_NAMES
}